### ISSUE TITLE
optimize renovate config

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/graphqlgen#416]
Agree with https://github.com/prisma/graphqlgen/pull/410#issuecomment-457865490 that renovate noise on master branch is too high.

Would like to try [a config](https://renovatebot.com/docs/configuration-options/) that would achieve:

#### prod deps

- immediate PRs per major, minor updates
- one consolidated weekend PR for all patch updates

#### dev deps

- immediate PRs per major update
- one consolidated weekend PR for all minor, patch updates

**Comment by jasonkuhrt** [comment]
Beta feature that might be interesting to try:

https://github.com/renovatebot/renovate/issues/2958

Instead of weekend PRs we can also do a living aggregate PR.

**Comment by koenpunt** [comment]
A living aggregate PR sounds like a good idea. 

Also, the only updates that are actually important are patches. 

Major versions should be aligned with the current state of the ecosystem. For example; a major update of graphql could make it required for users using graphqlgen to update their graphql dependency as well, otherwise there will exist multiple versions of graphql, which in turn causes issues with types being compared across versions, which will raise errors.
